export const recipeCategories = [
  {name:"African", imageSrc:"https://img.icons8.com/dotty/200/elephant.png"},
  {name:"Asian", imageSrc:"https://img.icons8.com/ios/200/rice-bowl.png"},
  {name:"American", imageSrc:"https://img.icons8.com/ios/200/hamburger.png"},
  {name:"British", imageSrc:"https://img.icons8.com/quill/200/british-pound.png"},
  {name:"Cajun", imageSrc:"https://img.icons8.com/carbon-copy/200/pepper-shaker.png"},
  {name:"Caribbean", imageSrc:"https://img.icons8.com/ios/200/coconut-cocktail.png"},
  {name:"Chinese", imageSrc:"https://img.icons8.com/ios/200/chinese-fried-rice.png"},
  {name:"Eastern European", imageSrc:"https://img.icons8.com/dotty/200/euro-pound-exchange.png"},
  {name:"European", imageSrc:"https://img.icons8.com/windows/200/flag-of-europe.png"},
  {name:"French", imageSrc:"https://img.icons8.com/ios/200/croissant.png"},
  {name:"German", imageSrc:"https://img.icons8.com/ios/200/german-house.png"},
  {name:"Greek", imageSrc:"https://img.icons8.com/external-flatart-icons-solid-flatarticons/200/external-greek-travel-flatart-icons-solid-flatarticons.png"},
  {name:"Indian", imageSrc:"https://img.icons8.com/external-victoruler-outline-victoruler/200/external-indian-occupation-and-people-victoruler-outline-victoruler.png"},
  {name:"Irish", imageSrc:"https://img.icons8.com/pastel-glyph/200/leprechaun.png"},
  {name:"Italian", imageSrc:"https://img.icons8.com/wired/200/italian-pizza.png"},
  {name:"Japanese", imageSrc:"https://img.icons8.com/dotty/200/pagoda.png"},
  {name:"Jewish", imageSrc:"https://img.icons8.com/ios/200/star-of-david.png"},
  {name:"Korean", imageSrc:"https://img.icons8.com/carbon-copy/200/south-korea.png"},
  {name:"Latin American", imageSrc:"https://img.icons8.com/ios/200/brazil.png"},
  {name:"Mediterranean", imageSrc:"https://img.icons8.com/fluency-systems-regular/200/greek-salad.png"},
  {name:"Mexican", imageSrc:"https://img.icons8.com/ios/200/sombrero.png"},
  {name:"Middle Eastern", imageSrc:"https://img.icons8.com/ios/200/rug.png"},
  {name:"Nordic", imageSrc:"https://img.icons8.com/ios/200/cross-flag.png"},
  {name:"Southern", imageSrc:"https://img.icons8.com/dotty/200/usa.png"},
  {name:"Spanish", imageSrc:"https://img.icons8.com/ios/200/tapas.png"},
  {name:"Thai", imageSrc:"https://img.icons8.com/external-justicon-lineal-justicon/200/external-thai-thailand-element-justicon-lineal-justicon-1.png"},
  {name:"Vietnamese", imageSrc:"https://img.icons8.com/external-ddara-fill-ddara/200/external-woman-tradition-dress-ao-dai-Vietnamese-national-costume-avatar-ddara-fill-ddara.png"}
];
